ghactions: Add Web UI tests
Add tests to validate that the Web UI container image can start and
service requests

diff --git a/.github/workflows/build-and-test.yaml b/.github/workflows/build-and-test.yaml
--- a/.github/workflows/build-and-test.yaml
+++ b/.github/workflows/build-and-test.yaml
@@ -387,6 +387,49 @@ jobs:
         run : |
           podman run --rm -it localhost/bitbake-hashclient-container-image:latest --help
 
+  webui-image-test:
+    needs:
+      - build
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Download Server OCI image
+        uses: actions/download-artifact@v3
+        with:
+          name: "bitbake-hashserver-${{ env.CONTAINER_ARCH }}-oci"
+
+      - name: Copy Server image to docker
+        run: |
+          skopeo copy oci-archive:bitbake-hashserver-${CONTAINER_ARCH}-oci.tar docker-daemon:bitbake-hashserver:latest
+
+      - name: Download Web UI OCI image
+        uses: actions/download-artifact@v3
+        with:
+          name: "bitbake-hashserver-web-ui-${{ env.CONTAINER_ARCH }}-oci"
+
+      - name: Copy Web UI to docker
+        run: |
+          skopeo copy oci-archive:bitbake-hashserver-web-ui-${CONTAINER_ARCH}-oci.tar docker-daemon:bitbake-hashserver-web-ui:latest
+
+      - uses: actions/checkout@v3
+        with:
+          path: meta-bitbake-hashserver
+
+      - name: Start containers
+        working-directory: ./meta-bitbake-hashserver/test/web-ui/
+        run: |
+          docker-compose up --detach
+
+      - name: Check server is running
+        run: |
+          for i in $(seq 10); do
+            if curl -v http://localhost:8000/; then
+              exit 0
+            fi
+            sleep 10
+          done
+          echo "Unable to connect to server"
+          exit 1
+
   publish:
     if: github.event_name == 'push'
     needs:
@@ -394,6 +437,7 @@ jobs:
       - image-ptest
       - server-image-test
       - client-image-test
+      - webui-image-test
       - yocto-check-layer
 
     permissions:
